### ISSUE TITLE
1820a bt The apple mouse sometimes gets stuck

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#13]
1820a bt The apple mouse sometimes gets stuck

**Comment by Juan-VC-gh** [comment]
Cannot verify this, I would recommend getting a stable bt card, dw1820a is known for issues. Best card to get is bcm94360ngw because macos comes with its firmware, else a bcm94352z.

**Comment by junguoguo2017** [comment]
i agree

**Comment by junguoguo2017** [comment]
I have bought a 942352z on taobao, it is too expensive. Can it be used directly?

**Comment by junguoguo2017** [comment]
I found that BCM94360CS2 can also be plugged in. Is the card stable?

**Comment by Juan-VC-gh** [comment]
It is, but it takes so much space it doesn't fit in the laptop + you need a PCIe to m.2 2230 adapter. Way better to buy a Broadcom m.2 2230 card.

**Comment by junguoguo2017** [comment]
1820a bluetooth will conflict with wifi2.4g, download files, when using a large network, will cause bluetooth intermittent jam. That's the problem with my apple mouse. Can look at this article, http://bbs.pcbeta.com/forum.php? Mod = viewthread&tid = 1822379. Does 94352z/1560,94360cs2 also have such problems?

**Comment by junguoguo2017** [comment]
1820a bluetooth will conflict with wifi2.4g, download files, when using a large network, will cause bluetooth intermittent jam. That's the problem with my apple mouse. Can look at this article, http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1822379. Does 94352z/1560,94360cs2 also have such problems?

**Comment by Juan-VC-gh** [comment]
oh true that could be the issue and will happen with any wifi/bt card unless you try signals of different frequencies so they don't get interferences.
