### ISSUE TITLE
Bootcamp opencore is problematic, but clover is normal

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#18]
![31F5824E-B9AA-43C1-818B-5E444524BBBB](https://user-images.githubusercontent.com/27845506/81790621-377f0580-9538-11ea-93d1-3489caed849a.png)

**Comment by junguoguo2017** [comment]
I installed 10.15.4 with opencore recently, and it is no problem that your clover installed 14.6 before. There are water ripples on the laptop screen。
![1111](https://user-images.githubusercontent.com/27845506/81792459-aa897b80-953a-11ea-9f4f-4b04488a95a3.PNG)

**Comment by Juan-VC-gh** [comment]
OpenCore related issue. Closed.
