### ISSUE TITLE
Is hdrmi supported?

### ISSUE THREAD

**Issue by Wanderson-Magalhaes** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#19]
First, thanks for sharing, the system installed perfectly without any errors! <3

But I was unable to use my HDMI connection, is it supported?
And what Kext or procedure should I do, I couldn't find a solution on Google.

**Comment by Juan-VC-gh** [comment]
Glad it worked for you! It is stated in the nonworking section: No HDMI video/audio output. It is controlled by the Nvidia discrete GPU. There are only Cuda drivers prior Mojave (10.14), nor pascal neither Turing cards will work. The Nvidia card is disabled by an ACPI call (_OFF) at the device scope (_SB.PCI0.PEG0.PEGP)

**Comment by Juan-VC-gh** [comment]
What I did was purchase a thunderbolt 3 to HDMI adapter which uses the intel GPU and voila I can use external screens! I hope that answers your question.

**Comment by Wanderson-Magalhaes** [comment]
> O que fiz foi comprar um adaptador Thunderbolt 3 to HDMI que usa a Intel GPU e pronto, posso usar telas externas! Espero que isso responda à sua pergunta.

Thank you very much, I will try to find an adapter to use on the Thunderbolt 3 output, glad that at least it is working.
Thank you. Excellent work!

**Comment by Wanderson-Magalhaes** [comment]
> What I did was purchase a thunderbolt 3 to HDMI adapter which uses the intel GPU and voila I can use external screens! I hope that answers your question.

Thank you very much, I will try to find an adapter to use on the Thunderbolt 3 output, glad that at least it is working.
Thank you. Excellent work!

**Comment by Juan-VC-gh** [comment]
Thanks, enjoy macOS!
