### ISSUE TITLE
High Sierra

### ISSUE THREAD

**Issue by anonychun** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#2]
Sorry I'm just beginner in Hackintosh, can I use this config for High Sierra installation?
My laptop is Dell G7 7588

**Comment by Juan-VC** [comment]
I haven’t done it but you could give it a try!

**Comment by Juan-VC-gh** [comment]
I haven’t tried it but unless you can disable your Nvidia card within the BIOS, then it works an Optimus card and will not work.
