### ISSUE TITLE
Is the inter bluetooth blocked?

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#22]
Was the inter bluetooth blocked? I replaced it with the inter network card, but I couldn't find the bluetooth

**Comment by Juan-VC-gh** [comment]
You must spell things correctly to make issues understandable, its intel card. Yes intel Bluetooth should not work, as it attaches to a different HS USB port which I did not include into my USB map kernel extension

**Comment by junguoguo2017** [comment]
yes, inter network card. Because now inter network card has a driver can be used perfectly. And inter wifi can also be used but not perfectly. So I tried to inject the bluetooth driver but it didn't work.

**Comment by junguoguo2017** [comment]
yes, inter network card. Because now inter network card bluetooth has a driver can be used perfectly. And inter wifi can also be used but not perfectly. So I tried to inject the bluetooth driver but it didn't work.

**Comment by Juan-VC-gh** [comment]
Recreate the USB map yourself, I do not have an intel card with me so I cannot create a map to use its Bluetooth. Injecting all ports in macOS is sometimes troublesome to easily check the USB port it attaches to, use windows.

**Comment by junguoguo2017** [comment]
I don't know anything about hackintosh, I just need SSDT, right?

**Comment by junguoguo2017** [comment]
Do I need to change usbmap.kext? I tried this address efi,inter bluetooth perfect. But I don't want to use this efi. It's not as good as yours.   https://github.com/flyfeng2002/FYQ-Hackintosh/tree/master/DELL-G7-7588/EFI-CLOVER/CLOVER/kexts/Other

**Comment by Juan-VC-gh** [comment]
Either modify my usbmap.kext to inject the port in which the Bluetooth attaches from the intel card or replace my kext with his. I did see he injects almost all HS ports which may lead to conflict.

**Comment by junguoguo2017** [comment]
Thank you, I have solved it

**Comment by junguoguo2017** [comment]
I have another question, where is the fan control, it seems that the cooling mechanism is not so friendly

**Comment by Juan-VC-gh** [comment]
Handled by macOS and UEFI, you must create one if you want fan control. I think there are some apps that I have never tried.

**Comment by junguoguo2017** [comment]
This is a profound problem that I don't think I can solve. Can you help me? Thank you very much

**Comment by Juan-VC-gh** [comment]
I do not plan going deep into fan control, anyway I am busy these days.
