### ISSUE TITLE
HiDPI not working

### ISSUE THREAD

**Issue by edassis** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#24]
I have a Dell G7 7588 (I did not change the wifi card).

I executed the `install.command` from Jack_Fix according with the section `Post-Installation`.

But the scale option isn't showing in the System Preferences>Built-in Display.

![image](https://user-images.githubusercontent.com/31329807/83558328-b7f5ae00-a4c7-11ea-9d09-6f8b73889d7c.png)

**Comment by Juan-VC-gh** [comment]
Where is the script your are executing located? Even tho I keep releases I never modified the script. It expects to be in /Downloads/Hackintosh-macOS-Catalina-on-Dell-G7-7588-master/Jack_Fix as if you would download the repo zip

**Comment by edassis** [comment]
I made sure to follow your guide strictly. I opened the script and saw that he expects that files are on "˜/Downloads/Hackintosh-macOS-Catalina-on-Dell-G7-7588-master/Jack_Fix". The script prompts all the passes as if was everything correct, and in the end prints a red message saying that he has completed.

I executed him twice already.

**Comment by Juan-VC-gh** [comment]
You need to disable csr with recovery for it to work, have you done so?

**Comment by edassis** [comment]
I'm that part now. I was afraid of continue without making previous steps correctly. I will try to disable csr and give you a feedback here.

**Comment by edassis** [comment]
I unlocked CSR and not solved. I ran the _Jack_Fix_ script again.

![CSR](https://user-images.githubusercontent.com/31329807/83569125-67e40f00-a4fa-11ea-8541-29b2adfb46d3.jpg)

![install.command](https://user-images.githubusercontent.com/31329807/83566430-5e58a800-a4f6-11ea-89a8-fd969d11bf96.png

**Comment by Juan-VC-gh** [comment]
Nice you have unlocked msr 0xe2 you can now achieve native cpupm, disable the mentioned kernel quirks in the cfg lock section to finally enable it. Unlocking cfg is different that csr (your picture shows unlocked cfg), recheck the section in which the HiDPI and jack script is mentioned. Csr is disabled into macos recovery.

**Comment by edassis** [comment]
I got shuffled with the acronymous kk. Yes, I have disabled CSR through recovery boot. I repeated the process just now to ensure:

![IMG_20200602_182305](https://user-images.githubusercontent.com/31329807/83572383-dc6d7c80-a4ff-11ea-8879-12d71d65ec52.jpg)

About CFG, I already adjusted kernel quicks as you instructed. Thanks for making the whole process as simple as possible.

**Comment by Juan-VC-gh** [comment]
CSR seems to be disabled now, rerun the script and restart, things will show huge at first but after selecting a resolution they will not anymore. Glad you got it working, enjoy the awesomeness of macOS!

**Comment by edassis** [comment]
Nope, not worked at all. Maybe I'm failing in some pre-requisites? Does the script need that the screen is in a specific resolution? Some configuration in the OS could affect the script?

The sound from jack output it's working perfectly.

**Comment by Juan-VC-gh** [comment]
Sound from jack does not require csr disabled so there might be an issue with something. Try the following:

in terminal: 
$sudo mount -uw /
$Killall Finder
$open -a finder /System/Library/Displays/Contents/Resources/Overrides/

Now manually rename Icons.plist to IconsBackup.plist
Create the folder DisplayVendorID-30e4 if not present already
Finally copy the following files from ~/Downloads/Hackintosh-macOS-Catalina-on-Dell-G7-7588-master/HiDPI_Files to their appropriate path

* Icons.plist to /System/Library/Displays/Contents/Resources/Overrides/
* DisplayProductID-5d0 to /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-30e4/
* DisplayProductID-5d0.icns to /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-30e4/

then reboot.

**Comment by Juan-VC-gh** [comment]
The script needs no specific resolution and I believe with the latest macOS Catalina 10.15.5 screen behaves the same, it might be your laptop shipped with a different screen, which will make the files I provided uselessly and would require an EDID extraction in Windows preferably.

**Comment by edassis** [comment]
I did as instructed. Not work too. You can give some help or point a tutorial about EDID extraction?

**Comment by Juan-VC-gh** [comment]
Check this out [DumpEDID](https://www.nirsoft.net/utils/dump_edid.html) attach a zip with the output to check the screen.

**Comment by Juan-VC-gh** [comment]
Using IORegistryExplorer should also work, I mostly need to check the productID and vendorID which are also dumped with the EDID. Launch the app and find AppleBacklightDisplay.

![AppleBacklightDisplay](https://iili.io/JO1Tmv.png)

**Comment by edassis** [comment]
Here is mine.

![Screen Shot 2020-06-02 at 23 32 40](https://user-images.githubusercontent.com/31329807/83589162-7138a000-a529-11ea-99d9-0700704f1327.png)

**Comment by Juan-VC-gh** [comment]
Indeed it does come with an LG display as well but it's a different one. Try to place the attached files manually, Icons.plist must be replaced, the other files have different names so no problem to keep both.
[HiDPI_Files.zip](https://github.com/Juan-VC/Hackintosh-macOS-Catalina-on-Dell-G7-7588/files/4720782/HiDPI_Files.zip)

**Comment by edassis** [comment]
Worked! Thank you very much, @Juan-VC. Congratulations for the awesome work!

**Comment by Juan-VC-gh** [comment]
Haha thanks, it's been a couple of hours. I will now close the issue, might add the files to the HiDPI folder, and modified the script so it can be executed anywhere.

**Comment by Juan-VC-gh** [comment]
Oh, I am not sure when did you install macOS but I pushed a commit today with kexts updates including a critical fix with VoodooI2C, it is recommended to update your files, it is safe to directly grab them from the master branch.

**Comment by edassis** [comment]
Updated. 👍
