### ISSUE TITLE
TrackPad getting touch from palm.

### ISSUE THREAD

**Issue by edassis** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#25]
I don't know if I missed up with any configuration or if this is the best that it can be on a Hackintosh. But I realized that when tipping, the trackpad still getting inputs from touch and even if I touch it lightly with my palm, it still getting the touch.

**Comment by Juan-VC-gh** [comment]
Hmm, not really sure about that, I do not get any input with my palm

**Comment by Juan-VC-gh** [comment]
Your issue points to be hardware-related and not a guide/macOS one
