### ISSUE TITLE
“hda-verb” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by edassis** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#27]
After some restarts of the system, this window begins to appear every time and always when I close this opens again:

<img width="488" alt="Screen Shot 2020-06-04 at 10 38 50" src="https://user-images.githubusercontent.com/31329807/83763893-9cb5aa80-a64f-11ea-8db9-f27b59e8aa0e.png">

I tried to execute the _install.command_ again, output:

> This Script Requires Administrator Privileges!
> Password:
> mount_apfs: volume could not be mounted: Operation not permitted
> mount: / failed with 77
> Copying files to fix ALC256 combojack noise issue
> cp: /usr/bin/JackFix: Operation not permitted
> chown: /usr/bin/JackFix: Operation not permitted
> Install JackFix:
> [##########################] (100%)
> 
> cp: /usr/bin/hda-verb: Operation not permitted
> chown: /usr/bin/hda-verb: Operation not permitted
> Install hda-verb:
> [##########################] (100%)
> 
> Install jack.fix.plist:
> [##########################] (100%)
> 
> override rw-r--r--  root/wheel for IconsBackup.plist? (y/n [n]) 
> not overwritten
> mkdir: DisplayVendorID-30e4: File exists
> Copying files to enable native HiDPI resolutions
> cp: /System/Library/Displays/Contents/Resources/Overrides/Icons.plist: Operation not permitted
> Install Icons.plist:
> [##########################] (100%)
> 
> cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-30e4/DisplayProductID-5d0: Operation not permitted
> Install DisplayProductID-5d0:
> [##########################] (100%)
> 
> cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-30e4/DisplayProductID-5d0.icns: Operation not permitted
> Install DisplayProductID-5d0.icns:
> [##########################] (100%)
> 
> cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-30e4/DisplayProductID-540: Operation not permitted
> Install DisplayProductID-540:
> [##########################] (100%)
> 
> cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-30e4/DisplayProductID-540.icns: Operation not permitted
> Install DisplayProductID-540.icns:
> [##########################] (100%)
> 
>  Successfully installed, reboot now to take effect! 
>  Appreciate the work? Consider donating -> https://www.paypal.me/juanvasquezcastro
>

I applied `chmod +x` to install script, didn't help.

**Comment by edassis** [comment]
I didn't realize that CSR auto-enabled again. Disabling solve the problem.

**Comment by Juan-VC-gh** [comment]
That is uncommon I have never seen System Integrity Protection re-enable by default. If you happen to face the same problem try disabling gatekeeper (protects the system from unsigned or not properly signed app) with the command `sudo spctl --master-disable`

**Comment by edassis** [comment]
It's because I'm trying to dual boot MacOS and Windows in the same disk. This happened when I booted MacOS after logged out Windows.

**Comment by Juan-VC-gh** [comment]
Not sure if that’s the case I dual boot with the sae NVMe and I have never seen the issue with people that dual boot with a single or multiple drives.

**Comment by edassis** [comment]
About dual booting, I can't start Windows from OpenCore boot menu, I have to select manually from the BIOS boot selection. I already tried to create an entry in `Misc -> Entries` for Windows with the following parameters:

![Entries config](https://user-images.githubusercontent.com/31329807/83809677-436c6c00-a68d-11ea-9aee-d4470b378408.png)

But, didn't even show the option. 

Before Opencore shows the boot menu, a message is printed very quickly in the screen. But it's too quickly that I'm not able to read it or take a picture.

- I enabled BootStrap for Windows stop messing with MacOS EFI files.

- `Microsoft`'s EFI folder is located in the same EFI partition of Mac EFI files.

**Comment by edassis** [comment]
Sorry, I didn't mean to open the issue again.

**Comment by Juan-VC-gh** [comment]
> About dual booting, I can't start Windows from OpenCore boot menu, I have to select manually from the BIOS boot selection. I already tried to create an entry in `Misc -> Entries` for Windows with the following parameters:
> 
> ![Entries config](https://user-images.githubusercontent.com/31329807/83809677-436c6c00-a68d-11ea-9aee-d4470b378408.png)
> 
> But, didn't even show the option.
> 
> Before Opencore shows the boot menu, a message is printed very quickly in the screen. But it's too quickly that I'm not able to read it or take a picture.

Covered in the guide, that is rEFInd for. Booting Widows with OC would require further tweaks to the ACPI tables.

**Comment by Juan-VC-gh** [comment]
To improve the booting process disable Show Picker in OC `config.plist` so it goes right from rEFInd to booting macOS kernel, make sure macOS is the first entry in OC because it's the entry it boots when the GUI is disabled. I have also updated rEFInd section in requirements to explain from it that it is needed for multi-boot instead of having that in setting up rEFInd.

I do think it was not completely clear it was the solution for multi-boot so changes were made.

**Comment by edassis** [comment]
Most guides/tutorials that I found didn't explain about multibooting properly (for example, I didn't know about the necessities of change in ACPI table). And was a little overwhelming to install Windows neighboring MacOS (Windows install script creates a bunch of partitions and always was giving me errors). Until I found a tutorial that explained how to do it from terminal allowing me to have Windows installed properly.

**Comment by edassis** [comment]
How I change the boot order in OpenCore's menu? Windows it's my first one.

**Comment by Juan-VC-gh** [comment]
Not sure about the windows problems you have when installing it normally but I do install it with the setup guide and will still work when multibooting. The easiest way to make macOS entry first is to either delete the windows entry if you added it manually to OpenCore config file or hide it.
