### ISSUE TITLE
Help with 7590?

### ISSUE THREAD

**Issue by carlosxfigueroa** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#30]
followed your guide (very well done) and first try everything booted, I believe the only things that need to be done are disabling the rtx 2070 max-q properly and getting ethernet to work, im not very knowledgable wiht patching but I believe I can be helpful to get full support for the 7590 if you are willing of course. even sleep/trackpad/keyboard work fine (during installer also) sometimes you cant change brightness with keys but its very minor bugs id love to help iron out

**Comment by Juan-VC-gh** [comment]
Sure I could take a look at the system files. How do you know the RTX 2070 isn't disabled? Please attach a full ACPI dump from the system and type the built-in ethernet chip to properly help you. For ACPI table dump, use [SSDTTime](https://github.com/corpnewt/SSDTTime) while on windows. Hope we can get those things sorted! I am amazed how similar the systems are, just do NOT try to unlock CFG before actually checking the bit offset.

**Comment by Juan-VC-gh** [comment]
It seems SSDTTime only dumps the main table (DSDT) which is fine, the GPU will most likely be there.
