### ISSUE TITLE
Not booting, at a loss.

### ISSUE THREAD

**Issue by cole2kb** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#31]
Hi, I've followed the guide's instructions several times, double-checked my BIOS settings, not really sure why but I just can not get the USB to boot. I add OpenCore.efi to my boot options and move it up to the top, I see the activity light run on my USB drive for a tiny bit before the laptop just boots into windows. If I open up my boot options menu and manually select OpenCore, it just reboots immediately. Any ideas?

Thanks.

**Comment by Juan-VC-gh** [comment]
Dang booting problems are somehow how to debug and it's harder if I just don't have my hands on the PC. I will double test the latest release just to confirm they at least work on my machine.

**Comment by cole2kb** [comment]
It was my own fault, nothing with the installer. I either missed entirely or it's not written in the guide that both the BOOT and the OC folders need to be copied, I was only copying the OC folder previously. Booting fine now. Thank you!

**Comment by Juan-VC-gh** [comment]
Dang, I am not even sure why it worked like that haha BOOT.efi is used as a default booting when there are no boot entries. At least it is working for you now!
