### ISSUE TITLE
bcm94352z  can't work

### ISSUE THREAD

**Issue by carsonlius** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#32]

**Comment by carsonlius** [comment]
the bluetooth is fine and the system is 10.14.6;
what can i do?

**Comment by carsonlius** [comment]
![Uploading image.png…]() 截图

**Comment by carsonlius** [comment]
I don‘t kwon how  but it is fixed now

**Comment by Juan-VC-gh** [comment]
I do not understand the issue, anyways better upgrade to catalina as I do not test the software in different macOS versions
