### ISSUE TITLE
Is the a guide or image iso using windows 10?

### ISSUE THREAD

**Issue by krishnasen2401** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#36]
Is there a preconfigured installer image for dell G7 7588 i7 variant or guide for creating installer using windows 10 itself without MAC system or MAC VM?

**Comment by Juan-VC-gh** [comment]
There is not, I am too lazy to upload a configured installer image. If you are going to do it with windows there are tools native w10 tools so you do not need a vm though I have not used them so if they do not work for you, create a vm.
