### ISSUE TITLE
Refind

### ISSUE THREAD

**Issue by dedwards77** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#39]
Hi, I have followed the guide to install BigSur and everything going good with one issue. I cant get extra entries for refind bootloader to delete. The hashtag is in the conf file yet when I try to delete extra entries the screen blinks and is still there. I was able to delete extra entries when I used the guide to install Catalina. Any suggestions? EDIT: I was able to fix this by adding hidden_tags to the showtools option in the conf file.

**Comment by Juan-VC-gh** [comment]
Hey, dropped rEFInd with the latest release so OC is the only one needed, try again with setting oc only
