### ISSUE TITLE
Audio problem has beed fixed

### ISSUE THREAD

**Issue by Shiyang-Wang** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#4]
the problem of audio work intermittently has been fixed, look at https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/17

**Comment by Juan-VC-gh** [comment]
Those are really good news! Using built from master AppleALC and committed on the dw1820a-aspm-disable branch after some more testing of the new version of the kext will commit on the master branch. Will also pick a new bcm94352z this weekend and commit if it works on the master branch as I should be able to have aspm enabled on macOS unlike with the dw1820a.
