### ISSUE TITLE
Temp of ssd that installed hackintosh was very hot

### ISSUE THREAD

**Issue by syah769** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#40]
![s](https://user-images.githubusercontent.com/37147869/102988596-17440a00-454f-11eb-9822-a1be02402dde.PNG)

After using the macOS, I tried to boot in windows back . In my Kingston has windows and samsung evo has macOs. Suddenly I noticed the temperature of samsung evo was very high. You can refer based on my screenshot. I dont know why. All functions work perfectly but it's spoiled in temperature. Hmm

**Comment by nguyenviethoang2020** [comment]
Its normal with nvme pcie 3.0. May you can use thermal pad to reduce temp.

**Comment by Juan-VC-gh** [comment]
Evo+ SSDs are known to cause some problems. Check NVMeFix driver by acidanthera, if that does not do it then you might want to replace it.
