### ISSUE TITLE
wifi problem

### ISSUE THREAD

**Issue by le332313** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#44]
Can you provide Intel network card EFI

**Comment by Juan-VC-gh** [comment]
Well i do not have my intel card to test that

**Comment by ishubhamsinghsp** [comment]
@le332313 You can use https://github.com/OpenIntelWireless/itlwm/releases for intel wifi card, works great for me, I am using Airportitlwm

**Comment by Juan-VC-gh** [comment]
> @le332313 You can use https://github.com/OpenIntelWireless/itlwm/releases for intel wifi card, works great for me, I am using Airportitlwm

Can you open a pull request with the changes in a new folder in the root of the repo called IntelWifiBT? I fear to make a mistake and push a non working setup. I could then check it and maintain it.

Thanks!

**Comment by ishubhamsinghsp** [comment]
Sure, will do that.

**Comment by ishubhamsingh** [comment]
Here's the PR with my OC directory https://github.com/Juan-VC/Hackintosh-macOS-Dell-G7-7588/pull/45

**Comment by Juan-VC-gh** [comment]
Actually push the IntelWifiBT folder inside the OptionalConfig one i created so it makes more sense.

Thanks!

**Comment by Juan-VC-gh** [comment]
Nvm I see the pr already haha I will take care of that later today. Thanks again.

**Comment by ishubhamsingh** [comment]
I have updated the PR anyway.

**Comment by Juan-VC-gh** [comment]
Thanks to @ishubhamsingh, try now replacing the files inside `OptionalConfig/IntelWifiBT` @le332313
