### ISSUE TITLE
Adding Intel WiFi and BT failed to start

### ISSUE THREAD

**Issue by 5158py** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#46]
Add Intel WiFi and BT Kexts can't start, stay in apple all the time。
I added https://github.com/Juan-VC/Hackintosh-macOS-Dell-G7-7588/blob/main/OptionalConfig/IntelWifiBT/OC/config.plist

**Comment by Juan-VC-gh** [comment]
It is hard for the to debug the issue since I no longer own an intel card. Can you try using the default config, then replacing first the config only and if it boots then the kexts? Best would be if you could activate debug with opencore to catch where the booting process stalls

**Comment by 5158py** [comment]
Use the default config, replace intel kexts to modify the default config！Thank you！

**Comment by Juan-VC-gh** [comment]
Did it work for you? I am not sure if I understood you

**Comment by 5158py** [comment]
Add to Intel kexts can be started, but intelwifi config cannot be started. Yes it worked

**Comment by Juan-VC-gh** [comment]
Not quite sure if I got that right. Does the intel wifi work for you now?

**Comment by 5158py** [comment]
intel wifi can work, but wifi can only run to 60 mbs and Bluetooth can also work

**Comment by Juan-VC-gh** [comment]
Oh yeah intel wifi and bluetooth drivers have some limitations at the moment. Will close the issue for now.
