### ISSUE TITLE
Disk Utility don't show

### ISSUE THREAD

**Issue by dany2709** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#50]
When I choose to install mac big sur and the icon appears if Apple is loading, then Disk Utility should exit but it does not show it. Thank you

**Comment by Juan-VC-gh** [comment]
I didn't understand your issue. Post a picture and explain it further.

**Comment by dany2709** [comment]
I was finally able to install big sur. Now I find that the sound volume is low
