### ISSUE TITLE
Software Update not showing new version of macOS

### ISSUE THREAD

**Issue by vinhtq115** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#51]
Currently, I'm on macOS Big Sur 11.4 and the latest version available now is 11.5.1. However, when opening Software Update, it shows that mine is currently up-to-date, instead of showing 11.5.1 update.

Previously, I also met this issue when I was at 11.1 and 11.3. I thought that it was my machine error so I did a clean install to update. But it seems that something is blocking the Software Update.

Is there anyway to fix this?

**Comment by Juan-VC-gh** [comment]
Hey @vinhtq115 I also faced this issue once and it was SIP related if I can recap properly.

Try setting in OpenCore **config.plis**->**Security**->**SecureBootModel**->**Disabled**

Let me know if it did the trick for you, I may just disable it by default for everyone so no one gets that problem again, it has to do with the missing T2 chip.

**Comment by vinhtq115** [comment]
> Hey @vinhtq115 I also faced this issue once and it was SIP related if I can recap properly.
> 
> Try setting in OpenCore **config.plis**->**Security**->**SecureBootModel**->**Disabled**
> 
> Let me know if it did the trick for you, I may just disable it by default for everyone so no one gets that problem again, it has to do with the missing T2 chip.

I set it to disabled but Software Update still says that macOS is up-to-date.

**Comment by vinhtq115** [comment]
So, I re-enabled SecureBootModel, set **config.plist**->**Misc**->**Security**->** BlacklistAppleUpdate** to `Disabled` and then reset NVRAM. After that, I went to Software Update. At first, it still not showing new updates. It showed that

> Updates for this mac are managed by swscan.apple.com

and asked me either to Restore Defaults or Cancel. I hit Cancel, went back to System Preferences and then Software Update and it showed 11.5.1.

I will update and see if there are any issues.

**Comment by Juan-VC-gh** [comment]
Right I remember now I had to reset NVRAM as well tho not of the **BlacklistAppleUpdate** didn't remember that was enabled, will disable it by default with the next release

**Comment by vinhtq115** [comment]
I updated to 11.5.1 and everything was fine. No issues at all. Not sure why OpenCore developers decided to enable that flag since 0.6.4.

**Comment by vinhtq115** [comment]
I updated to 11.5.1 and everything was fine. No issues at all. Not sure why OpenCore developers decided to enable that flag since 0.6.4.

**Comment by Juan-VC-gh** [comment]
Not sure either but will disabled it with the next release. Thanks!

**Comment by Juan-VC-gh** [comment]
You know @vinhtq115 it might have been the nvram reset and not the **BlacklistAppleUpdate** I see many people can update with it enabled including myself which I updated to 11.5.1 even before you

**Comment by 13thdemarch** [comment]
> You know @vinhtq115 it might have been the nvram reset and not the **BlacklistAppleUpdate** I see many people can update with it enabled including myself which I updated to 11.5.1 even before you

because of SIP value. I dont know why but if you guys want to check new macOS update correctly, even if BlacklistAppleUpdate is enabled, you have to make the SIP enabled (value 0000000). I haven't tried to check the update which let SIP with that value but disable the SIP in Recovery.  But currently on Hackintosh, if you want to check and update new macOS, have to enable SIP. That's what I know xD
