### ISSUE TITLE
Found two sound outputs, one of which has no sound

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#52]
Found two sound outputs, one of which has no sound.
<img width="288" alt="企业微信20210818-182021@2x" src="https://user-images.githubusercontent.com/27845506/129881986-756c8c88-ed17-462b-b100-93bd0d213b8b.png">

**Comment by Juan-VC-gh** [comment]
This is true, I have seen it before although never really cared for fixing it because it is a minor issue.

**Comment by 13thdemarch** [comment]
this is because of layout-id 14. There are 2 outputs, one for internal speaker, one when you plugged the headphone or any audio devices via 3.5 jack. This is not bug, it's the feature of layout-id 14 .-.

**Comment by Juan-VC-gh** [comment]
Oh then I guess it switches automatically because I have never have to do so manually and therefore never noticed 2 outputs
