### ISSUE TITLE
Check this option, unplug the mouse, the trackpad is not available

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#53]
Check this option, unplug the mouse, the trackpad is not available.
![image](https://user-images.githubusercontent.com/27845506/129915969-41b5d645-8263-44bc-aee3-d8314b3bd709.png)

**Comment by Juan-VC-gh** [comment]
I had never activated this Accessibility option but I was able to reproduce the issue, as the two sound outputs I believe it is a minor issue and this is one is probably more related to the trackpad driver that might not be really worth the time looking into.
