### ISSUE TITLE
OC can enter recovery mode but keep restarting after choosing macOS install

### ISSUE THREAD

**Issue by ehxu** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#54]
I used the USB flash drive made with the installation files in the AppStore. When I choose OC to boot, I can enter the installation mode normally. After waiting ten minutes to copy the installation files from the USB flash drive to the local hard disk, wait for the restart to enter the installation formally, but after choose the install macOS entry and The machine will keep restarting and unable to enter the system. Please help me, thanks.

**Comment by Juan-VC-gh** [comment]
Yout BIOS settings are either wrong or your laptop is not a Dell G7 7588 instead another Dell G7 model. Anyways if you have another model configure OC for debug and check the errors.

**Comment by ehxu** [comment]
The computer model is indeed G7 7588. After carefully reviewing the documentation, it is found that the CFG Lock setting failed. Now it can be installed normally, thanks!

**Comment by Juan-VC-gh** [comment]
Oh yeah CFG Lock was also an issue to go into a restart loop, well good to know it works for you now!
