### ISSUE TITLE
HEVC  decode

### ISSUE THREAD

**Issue by Superfly12138** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#55]
my laptop is G7 7590,i7 8750h uhd630.using the same oc as you.but it not works with hevc hard decoding,h.264 works well.
<img width="879" alt="截屏2021-09-02 上午12 43 10" src="https://user-images.githubusercontent.com/23469346/131711171-f9dd459a-5afc-44a6-badd-752137a885cd.png">

**Comment by Superfly12138** [comment]
I use an external 4K monitor，and a built-in display。

**Comment by Juan-VC-gh** [comment]
Right I verified that was an ongoing issue, fixed it for now. You can adapt your config using the gpu entry attached in the file or wait for the next release. PlistEdit Pro is great for this.

[config.zip](https://github.com/Juan-VC/Hackintosh-macOS-Dell-G7-7588/files/7110190/config.zip)

It should work with your G7 7590 now.

**Comment by Superfly12138** [comment]
thank you very much! appreciate for your work.

**Comment by Juan-VC-gh** [comment]
Good to know!, let me know if it solves the issue for you.

**Comment by Superfly12138** [comment]
when using the config you given,hevc decode works.
![截屏2021-09-05 下午2 20 25](https://user-images.githubusercontent.com/23469346/132117617-950a9f14-b8b2-44fc-afa1-5e429a7b876e.png)
but,my 4k monitor doesn't have 3840x2160 resolution and hidpi.
before 
![截屏2021-09-05 下午2 16 26](https://user-images.githubusercontent.com/23469346/132117635-2530a3c8-e397-429e-9666-d264c9a8ae83.png)
after
![截屏2021-09-05 下午3 28 58](https://user-images.githubusercontent.com/23469346/132119113-0b664b77-f055-4c6b-aedc-90aa265cff19.png)

and i using RDM to adjusting the resolution,however ,it doesn't have.
![截屏2021-09-05 下午2 26 01](https://user-images.githubusercontent.com/23469346/132117665-c4407ef2-facd-401d-901a-3fd07da8beda.png)

**Comment by Juan-VC-gh** [comment]
HiDPI is hardware dependent, there is some software which can help emulate it but do not remember it’s name.

**Comment by 13thdemarch** [comment]
> when using the config you given,hevc decode works.
> ![截屏2021-09-05 下午2 20 25](https://user-images.githubusercontent.com/23469346/132117617-950a9f14-b8b2-44fc-afa1-5e429a7b876e.png)
> but,my 4k monitor doesn't have 3840x2160 resolution and hidpi.
> before
> ![截屏2021-09-05 下午2 16 26](https://user-images.githubusercontent.com/23469346/132117635-2530a3c8-e397-429e-9666-d264c9a8ae83.png)
> after
> ![截屏2021-09-05 下午3 28 58](https://user-images.githubusercontent.com/23469346/132119113-0b664b77-f055-4c6b-aedc-90aa265cff19.png)
> 
> and i using RDM to adjusting the resolution,however ,it doesn't have.
> ![截屏2021-09-05 下午2 26 01](https://user-images.githubusercontent.com/23469346/132117665-c4407ef2-facd-401d-901a-3fd07da8beda.png)

try to enable HiDPI for your external monitor using this script from xzhih:
https://github.com/xzhih/one-key-hidpi

**Comment by Juan-VC-gh** [comment]
Yes this script can create files to emulate HiDPI for your external display
