### ISSUE TITLE
Pink screen

### ISSUE THREAD

**Issue by dany2709** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#57]
About two months ago I use Hackintosh but now it shows me the pink screen for a few minutes. Any idea of ​​the problem?
https://user-images.githubusercontent.com/37417178/134279471-6a7c696e-9b11-4e5d-bc87-523129d403d4.mp4

**Comment by Juan-VC-gh** [comment]
I have not yet faced the issue you mention, nor everyone else or I would have expected an open issue so I recommend you to update OC with the latest repo release and if it is not fixed then reinstall macOS from scratch.
