### ISSUE TITLE
New method for 3.5mm jack port audio output

### ISSUE THREAD

**Issue by 13thdemarch** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#58]
Thanks for your codec_dump, I found a new method to get 3.5mm port work, using ALCPlugFix-Swift. Some other ALC256 machines only need ALCPlugFix-Swift to work (I tested with Dell 5577 by myself), but on this G7, it needs both CodecCommander and SSDT-ALC256, to be paired with ALCPlugFix. But also it gives a better audio output, similar to Windows in my opinion.
You can check it here in my repository: 
https://github.com/akisame-reiu/Dell-Inspiron-G7-7588-Hackintosh/tree/main/Post-Install/ALCPlugFix-Swift

**Comment by Juan-VC-gh** [comment]
This is definitely really good just because it is a codeless solution, I like the kernel to be as small as possible.

Just tries it and worked without an issue with both pin 0x21 and 0x24. Did not find any differences between these pins, have you?

Thanks for the suggestion this is appreciated!, will update the repo with this solution in the next few days.

**Comment by 13thdemarch** [comment]
I only focus on 2 key-value:
- Node 0x19, pin 0x24: This one is headset, which means it makes the audio out only, there is no external mic.
- Node 0x1a, pin 0x20: This one is combojack, which means one jack for both external audio out and mic.
But I prefer 0x19 pin 0x24 because SSDT-HDEF in my repo is SSDT-ALC256, which already included the default config for node 0x19 pin 0x24, to be paired with CodecCommander 😂

**Comment by Juan-VC-gh** [comment]
I see haha, seems to do the trick for now. Anyways, I love this solution because the smaller the kernel the more responsive a system  can be. Thanks for letting me know about this solution!

**Comment by 13thdemarch** [comment]
you're welcome man!
