### ISSUE TITLE
WiFi doesn't work in Monterrey

### ISSUE THREAD

**Issue by dany2709** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#59]
I just upgraded to macOS Monterrey and I find that the wifi does not work, it does not activate and when I go to the control panel -> network -> WiFi it shows a message "Error in preferences: An error occurred in the network preferences panel". I tried updating the EFI to version 0.1.8 and the problem persists

**Comment by Juan-VC-gh** [comment]
That really depends on the card. My BCM94352Z is working just fine, however there are still issues with some cards with both wifi and bt, these much-needed driver fixes should be carried by acidanthera team, or intel wifi/bt team respectively. Even though I got Wi-Fi working for example, bluetooth is only partially working.

**Comment by dany2709** [comment]
Fix the problem by adding the kext IO80211 2.0.0 version for Monterrey and everything works 100%

[IO80211 Monterrey - Github](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0)

**Comment by Juan-VC-gh** [comment]
Oh thanks for the info, will add this kext in the next update.

**Comment by Juan-VC-gh** [comment]
Hey Dany, can you specify all the kexts you used to get the intel wifi+bt working? Is it 3? Airportltlwm + IntelBluetoothFirmware + IO80211? It's to make sure I get all of them in the next update, also can you specify the load order as well?

**Comment by Juan-VC-gh** [comment]
> Fix the problem by adding the kext IO80211 2.0.0 version for Monterrey and everything works 100%
> 
> [IO80211 Monterrey - Github](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0)

Did not find any kernel extension named IO80211, is it the one called itlwm? Or did you mean BlueToolFixup?
