### ISSUE TITLE
AirportItlwm for wifi - bluetooth not working

### ISSUE THREAD

**Issue by peteralf** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#64]
-AC9560 Wifi is working with AirportItlwm.kext not with Itlwm
-bluetooth is not working at all ( With Bluebtoolfixup.kext + IntelBluetoothFirmware.kext )

**Comment by Juan-VC-gh** [comment]
I no longer have an intel card with me to test that. The testing I do is with Broadcom only so I cannot guarantee intel cards will work, if someone gets it working feel free to create a pull request to help intel wifi card folks.

**Comment by 13thdemarch** [comment]
@peteralf @Juan-VC some AC9560 cards have weird issue with intel wireless kext. To make sure, first should check its vendor-id and device-id if it's supported. Then try to use stable or alpha version and check which version the card runs smoothly. For example, my AC9560 now is running fine with both release/latest alpha version. And I recommend you should use AirportItlwm.
About bluetooth, check kext order, also USB mapping. Intel bt port is HS14, instead of Broadcom is HS07. IntelBluetoothFirmware should be loaded first, then BlueToolFixup. Also, there is no Injector kext at Monterey.

**Comment by peteralf** [comment]
Bluetooth is still not working even with HS14 instead of HS11 /07🫣 and loading BTfirmware then BTfixup

**Comment by 13thdemarch** [comment]
> Bluetooth is still not working even with HS14 instead of HS11 /07🫣 and loading BTfirmware then BTfixup
> 
> 

what OS version are you using? For Monterey only Firmware and BTFixup, but Big Sur and older should be Firmware and Injector
Also make sure in System Information > USB, the BT port is HCI.

**Comment by peteralf** [comment]
> > Bluetooth is still not working even with HS14 instead of HS11 /07🫣 and loading BTfirmware then BTfixup
> 
> what OS version are you using? For Monterey only Firmware and BTFixup, but Big Sur and older should be Firmware and Injector Also make sure in System Information > USB, the BT port is HCI.

I'm using Monterey
  Address:	NULL
  State:	Off
  Chipset:	BCM_4350C2
  Discoverable:	Off
  Firmware Version:	v0 c0
  Product ID:	0x0001
  Supported services:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  Transport:	USB
  Vendor ID:	0x004C (Apple)

**Comment by peteralf** [comment]
Bluetooth worked ..
-Rolled back to release 0.1.9
-using latest BlueToolFixup.kext and IntelBluetoothFirmware.kext
-Bluetooth map for intel is HS11
-Considering the right order of kexts to be loaded ( Intelfirmware.kext --> Bluetoolfixup )
OS : Monterey

**Comment by 13thdemarch** [comment]
> Bluetooth worked ..
> 
> -Rolled back to release 0.1.9
> 
> -using latest BlueToolFixup.kext and IntelBluetoothFirmware.kext
> 
> -Bluetooth map for intel is HS11
> 
> -Considering the right order of kexts to be loaded ( Intelfirmware.kext --> Bluetoolfixup )
> 
> OS : Monterey

wait, are you sure it is HS11? Because I have tried a lot types of wifi card and there are only 2 ports, HS14 for CNVI card like 9560AC and HS07 for PCIe card like DW1560, BCM94360NG, AX210,...

**Comment by peteralf** [comment]
> 

Yeah i'm pretty sure its the same map kext provided by juan HS11

**Comment by peteralf** [comment]
> > Bluetooth worked ..
> > -Rolled back to release 0.1.9
> > -using latest BlueToolFixup.kext and IntelBluetoothFirmware.kext
> > -Bluetooth map for intel is HS11
> > -Considering the right order of kexts to be loaded ( Intelfirmware.kext --> Bluetoolfixup )
> > OS : Monterey
> 
> wait, are you sure it is HS11? Because I have tried a lot types of wifi card and there are only 2 ports, HS14 for CNVI card like 9560AC and HS07 for PCIe card like DW1560, BCM94360NG, AX210,...

I also tired HS08 and alot of other things .. but when i rolled to 0.1.9 i tried again the HS11 and it worked !!

**Comment by 13thdemarch** [comment]
hmm, anyway congratz
but maybe I think Juan should check his map again 🙄

**Comment by peteralf** [comment]
> hmm, anyway congratz
> but maybe I think Juan should check his map again 🙄

Haha it was working in bigsur btw so why its changing now ? Is the port walking inside our laptops? 😂lol that was weird for me :D
