### ISSUE TITLE
Dell G7 7590

### ISSUE THREAD

**Issue by harika09** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#9]
Will this works on Dell 7590?

**Comment by Juan-VC-gh** [comment]
It will most likely work with a few changes: CPUFriendDataProvider.kext should be removed and optionally replaced with a proper one for the cpu, usbmap.kext may work or it may need a manually created usbmap. Igpu may need a fake id if cpu is 9th gen or later. Trackpad acpi device name may need changes, CFG lock bit offset will most likely need to be checked and other minor changes with acpi probably. You can try the repo with you machine and no harm will come to it, if it just doesn’t boot macos then try applying the modifications above.
